### ISSUE TITLE
install rabbitmq error.

### ISSUE THREAD

**Issue by zengxc-1996** [Websoft9/role_rabbitmq#1]
## not found rabbitmq 3.7 package:
![image](https://user-images.githubusercontent.com/63622990/118110709-577c2a00-b415-11eb-9c48-c89515ada525.png)

**Comment by zengxc-1996** [comment]
## An error was reported when installing RabbitMQ 3.6 dependencies
![image](https://user-images.githubusercontent.com/63622990/118111032-bb065780-b415-11eb-87c2-b8187e6ea623.png)

**Comment by qiaofeng1227** [comment]
Done
